# Site settings
title: ğ‘ğšğ§ğ£ğšğ§ ğŠğ®ğ¦ğšğ«
# description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: RÎ±Î·ÕµÎ±Î· KumÎ±r
user_description: Exá´˜á´‡Ê€Éªá´‡É´á´„á´‡á´… Rá´‡á´… Tá´‡á´€á´á´‡Ê€ á´¡Éªá´›Êœ 2 Êá´‡á´€Ê€s á´Ò“ É´á´‡á´›á´¡á´Ê€á´‹ á´€É´á´… á´¡á´‡Ê™ á´€á´˜á´˜ÊŸÉªá´„á´€á´›Éªá´É´ á´˜á´‡É´á´‡á´›Ê€á´€á´›Éªá´É´ á´›á´‡sá´›ÉªÉ´É¢ á´‡xá´˜á´‡Ê€Éªá´‡É´á´„á´‡. Aá´„Ç«á´œá´€ÉªÉ´á´›á´‡á´… á´¡Éªá´›Êœ AÉ´á´…Ê€á´Éªá´… á´€É´á´… API Pá´‡É´á´›á´‡sá´›ÉªÉ´É¢ . AÉ´ ÉªÉ´-á´…á´‡á´˜á´›Êœ á´‹É´á´á´¡ÊŸá´‡á´…É¢á´‡ á´Ò“ á´ á´œÊŸÉ´á´‡Ê€á´€Ê™ÉªÊŸÉªá´›Éªá´‡s á´€É´á´… á´Éªá´›ÉªÉ¢á´€á´›Éªá´É´ á´›á´‡á´„ÊœÉ´ÉªÇ«á´œá´‡s, É¢á´€ÉªÉ´á´‡á´… Ò“Ê€á´á´ á´ á´€Ê€Éªá´á´œs á´„á´‡Ê€á´›ÉªÒ“Éªá´„á´€á´›Éªá´É´s. WÉªá´›Êœ á´€ Ò“á´á´„á´œs á´É´ á´„ÊŸá´á´œá´… sá´‡á´„á´œÊ€Éªá´›Ê. I Ò“á´á´„á´œs á´É´ sá´›á´€ÊÉªÉ´É¢ á´œá´˜á´…á´€á´›á´‡á´… á´€É´á´… á´‡xá´˜á´€É´á´…ÉªÉ´É¢ á´Ê á´„ÊÊ™á´‡Ê€sá´‡á´„á´œÊ€Éªá´›Ê á´‹É´á´á´¡ÊŸá´‡á´…É¢á´‡
user_title: ğ–²ğ–¾ğ–¼ğ—ğ—‹ğ—‚ğ—ğ—’ ğ–±ğ–¾ğ—Œğ–¾ğ–ºğ—‹ğ–¼ğ—ğ–¾ğ—‹
email: ranjankumar6289@gmail.com
twitter_username: twitter.com/whoamiRANJAN
github_username:  github.com/kabir0104k
gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
